workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    scripts:
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
            --workspace "YourApp.xcworkspace" \
            --scheme "YourAppScheme"  # Replace with your Xcode scheme name
    artifacts:
      - build/ios/ipa/*.ipa
